name: XR Demo CI

on:
  push:
    branches:
      - main
      - "001-xr/**"
  pull_request:
    branches:
      - main
      - "001-xr/**"

jobs:
  quality:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: web/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Unit tests
        run: npm run test:unit -- --run

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium webkit

      - name: Smoke tests
        run: npm run test:smoke -- --headed

      - name: Visual regression tests
        run: npm run test:visual -- --headed

      - name: Accessibility tests
        run: npm run test:accessibility -- --headed

      - name: Performance tests
        run: npm run test:perf
